### ISSUE TITLE
[EPIC] Cosmos SDK v0.50 Upgrade

### ISSUE THREAD

**Issue by johnletey** [noble-assets/aura#1]
This will serve as a tracking issue for the upgrade work to Cosmos SDK v0.50

Work will be done in chunks, and pushed to the [`feat/sdk-eden`](https://github.com/noble-assets/aura/tree/feat/sdk-eden) feature branch.

**Comment by spoo-bar** [comment]
Task breakdown:

- [x] Update proto files to use the latest proto-builder image + relevant proto annotations in the actual files
- [x] Update all packages to cosmos-sdk v0.50.9 compatible versions
- [x] Update the package references in the codebase + e2e test codebase
- [x] Fixing all tests - assuming any broken now
- [ ] Migrate to use collections API
- [ ] Migrate to app.go v2
- [ ] Implement autocli
- [ ] Final formatting and linting and fixing any tests
